### ISSUE TITLE
pip install in a virtualenv fails

### ISSUE THREAD

**Issue by pancho-villa** [sentriz/betanin#96] opened 2023-08-14 03:02 UTC
Hello,

I tried to install betanin via pip inside of a virtualenv and it failed with this:

```
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for greenlet
  Running setup.py clean for greenlet
Failed to build gevent greenlet
ERROR: Could not build wheels for gevent, greenlet, which is required to install pyproject.toml-based projects
```

This with Python 3.11.4, and it seems more of a dependency issue, but I thought I'd let you know. 

Cheers

**Comment by sentriz** [comment] 2023-08-15 11:54
hm i can't reproduce this. in a fresh venv it works fine for me


https://github.com/sentriz/betanin/assets/6832539/bce3e383-0151-47e7-a2fc-8cf30e404534

**Comment by sentriz** [comment] 2023-08-15 14:53
i can try help if needs be with this. though closing for now

**Closed by sentriz** 2023-08-15 14:53 UTC
